mozilla-services/consvc-shepherd

- consvc_shepherd/models/contile.py
- consvc_shepherd/tests/test_models_contile.py
> feat: implement to_dict for partner, and advertiser models

- consvc_shepherd/settings.py
- requirements.in
- requirements.txt
> chore: remove merino related things from shepherd

- consvc_shepherd/tests/test_admin.py
- contile/models.py
- requirements.in
- requirements.txt
Added tests for coverage, this should techincally put line coverage at 95%
closes #24
> [CONSVC-1733] chore: added tests to ensure coverage

- .circleci/config.yml
- Dockerfile
- contile/tests/test_models.py
- requirements.in
- requirements.txt
Enables tests for circle.
Docker credentials are temp, since it's current using mine
closes #15
> [CONSVC-1709] chore: enable tests and coverage for circle

- consvc_shepherd/admin.py
- consvc_shepherd/tests/test_admin.py
> [CONSVC-1736] feat: add validation so that snapshots are only launched once

- consvc_shepherd/settings.py
> [CONSVC-2043]fix: settings to fix CSRF verification failure

- requirements.in
- requirements.txt
accidentally used "google" instead which is an unofficial one and not maintained
> fix: switch to official google auth library

- .circleci/config.yml
- Dockerfile
- version.json
> fix: add version.json so that /__version__ returns info

- .circleci/config.yml
- requirements.in
- requirements.txt
Trying to bring shepherd to baseline in comparison with our other python services 🙂
> added bandit

- .circleci/config.yml
- .dockerignore
- Makefile
also covers [DISCO-2156] since it's relatively small
[DISCO-2156]: https://mozilla-hub.atlassian.net/browse/DISCO-2156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2162] chore: provide shortcuts for frequently used tasks

- poetry.lock
- pyproject.toml
- scripts/README.md
- scripts/recover.py
Tried my best to clean this up... 🙈 
In the event, that multiple changes are made in Shepherd and its unclear how to revert the data to a previous state.
We can delete the Partner instance, which in result would delete all advertisers and ad_urls and run the script to set
data to back to values of a snapshot.
> feat: Added Recovery Script

- Dockerfile
- consvc_shepherd/admin.py
- consvc_shepherd/tests/test_admin.py
- schema/shepherd.schema.json
- schema/test_schema.py
So... this doesn't achieve the ability to keep contile and shepherd in sync in terms of the json structure, but it's a start?
> [DISCO-2267] Added json schema for Shepherd Output

- .circleci/config.yml
- consvc_shepherd/admin.py
- consvc_shepherd/tests/test_admin.py
- consvc_shepherd/tests/test_forms.py
- poetry.lock
- pyproject.toml
- schema/shepherd.schema.json
- schema/test_schema.py
As a result of tests not set in the circle config, we weren't able to detect, that there was missing dependencies and i broke existing tests
> Circle to actually run tests again

- .env.example
- README.md
Simple updates in `README` file for using pyenv virtualenv and some updates to running the server.
> [DISCO-2348] docs update

- Makefile
> chore: add env so 'make test' works locally

- templates/allocation/allocation_list.html
- templates/base.html
- templates/index.html
> feat: added nav bar

- contile/admin.py
> [DISCO-2364] chore: Add reminder to update SOV allocation when Partner is deleted

- consvc_shepherd/admin.py
- consvc_shepherd/forms.py
- consvc_shepherd/tests/test_forms.py
JIRA: [DISCO-2396](https://mozilla-hub.atlassian.net/browse/DISCO-2396)
Found out you could swap out the inline admin form 🙌 
[DISCO-2396]: https://mozilla-hub.atlassian.net/browse/DISCO-2396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DISCO-2396] feat: add validation guardrails to SOV forms

- consvc_shepherd/tests/test_views.py
> chore: rename test class for test view

- Makefile
- consvc_shepherd/tests/test_admin.py
Django struggles.... forgot that when branches that are behind main merges, we run into problems when there is a recent django migration
> chore: fix up migration

- Makefile
- openidc/middleware.py
- openidc/test_middleware.py
- schema/test_schema.py
Just some additional pydocs and typing
> chore: missing typing and pydocstyle

- consvc_shepherd/settings.py
> change env var declarations

- consvc_shepherd/models.py
- [X ] This PR conforms to the [Contribution Guidelines](https://github.com/mozilla-services/consvc-shepherd/blob/main/CONTRIBUTING.md).
> chore: remove unnecessary code and comment fix

- consvc_shepherd/forms.py
- consvc_shepherd/tests/test_views.py
- consvc_shepherd/urls.py
- consvc_shepherd/views.py
- templates/allocation/allocation_create_or_edit.html
- templates/allocation/allocation_list.html
Shuffling stuff off of django admin. I acknowledge there are some ux.... quirks?... the spacing between the delete checkbox for one. Would prefer to create follow ups for those
> feat: allocation setting forms ui

- contile/admin.py
The majority of paths are '/', saves some time to have '/' already as the default.
> chore: add '/' as default placeholder path

- README.md
- docs/SUMMARY.md
- docs/UserGuide.md
- docs/intro.md
- docs/quickStart.md
JIRA: [DISCO-2531](https://mozilla-hub.atlassian.net/browse/DISCO-2531)
GitHub: [#162](https://github.com/mozilla-services/consvc-shepherd/issues/162)
The Service Overview page in GitHub should contain the following information:
Architecture Diagram. Ideally the diagram is in Mermaid for ease of change and maintainability.
High level description of what the purpose of the service is.
Links to API documentation
What datastores should we be aware of? This can also just be part of the architecture diagram.
What external dependencies should we be aware of? (i.e. Shepherd etc.). This can also just be part of the architecture diagram.
[DISCO-2531]: https://mozilla-hub.atlassian.net/browse/DISCO-2531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> [DISCO-2531] GitHub landing page

- static/preview/css/preview.css
Forgot to run `collectstatic` before landing #196.
> Update previews CSS file

- Makefile
JIRA: [AE-538](https://mozilla-hub.atlassian.net/browse/AE-538)
Added a working help target and multiple new commands for migrations. This is also a first step in getting the Shepherd Makefile in alignment with the MARS file
[AE-538]: https://mozilla-hub.atlassian.net/browse/AE-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AE-538 makefile improvements

- consvc_shepherd/tests/test_preview.py
JIRA: [AE-539](https://mozilla-hub.atlassian.net/browse/AE-539)
Added unit tests for the get_unified function, which was previously uncovered and causing low test coverage for the preview file
[AE-539]: https://mozilla-hub.atlassian.net/browse/AE-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AE-539] Add unit test for get_unified function to improve coverage of the preview file

- PULL_REQUEST_TEMPLATE.md
We have a new Jira project for shepherd, let's update the PR template to reflect that.
- AE -> SHEP
- Use numbers for the issue placeholder
- Fix typos
> Update PR template for new SHEP Jira project

- Makefile
- ad-ops-dashboard/eslint.config.js
- ad-ops-dashboard/src/components/Forms/CampaignForm.tsx
- ad-ops-dashboard/src/components/Forms/SplitCampaignForm.tsx
- ad-ops-dashboard/src/components/Inputs/DateInput.tsx
- ad-ops-dashboard/src/components/Inputs/SelectInput.tsx
- ad-ops-dashboard/src/components/Inputs/TextInput.tsx
- ad-ops-dashboard/src/components/Layout/AppLayout.tsx
- ad-ops-dashboard/src/components/Layout/LayoutDrawer.tsx
- ad-ops-dashboard/src/config/routes.config.ts
- ad-ops-dashboard/src/data/campaigns.ts
- ad-ops-dashboard/src/data/deals.ts
- ad-ops-dashboard/src/data/products.ts
- ad-ops-dashboard/src/pages/CampaignOverview/CampaignOverview.tsx
- ad-ops-dashboard/src/pages/Dashboard/Dashboard.tsx
- ad-ops-dashboard/src/types.tsx
- ad-ops-dashboard/src/utils/schemas/campaignFormSchema.ts
- consvc_shepherd/api/serializers.py
[SHEP-123](https://mozilla-hub.atlassian.net/browse/SHEP-123)
Lint issues need to be fixed for the campaigns pages and components since the lint setup has been completed and merged.
1. Added lint fixes for the campaigns pages and their components
2. Enabled ESLint in the `make lint` command
run `make lint` command 
[SHEP-123]: https://mozilla-hub.atlassian.net/browse/SHEP-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SHEP-109] Fixed Linting Issues and Enabled Linting in Makefile
