mozilla-services/consvc-shepherd

.env.example
README.md
docker-compose.yml
requirements.in
requirements.txt

added a docker-compose file,  for people (and myself) who want to work with a docker work-flow

add docker-compose file

---

Dockerfile

Was accidentally removed in #44
closes #54

[CONSVC-2005] fix: dockerfile edit to copy openidc dir

---

consvc_shepherd/admin.py
consvc_shepherd/settings.py
consvc_shepherd/storage.py
consvc_shepherd/tests/test_admin.py

Introduce an env for the bucket file name
The idea is that every time a new snapshot is pushed, the existing file would be rewritten under a different file name with the original creation date appended to the name.
Thoughts?

Naming convention for bucket files

---

contile/models.py
contile/tests/test_models.py

was trying to automate inputting existing data into shepherd
hit into the following cases:
- urls like www.foo.co.uk were not allowed by shepherd
- paths /hello was not allowed for exacts
These currently exist in the contile settings, so I made changes to allow them

fix ad url validation

---

.env.example
consvc_shepherd/settings.py
openidc/middleware.py
openidc/test_middleware.py

`X-Goog-Authenticated-User-Email` returns value of format `accounts.google.com:example@gmail.com`
So we need to remove that before going ahead and creating a user
ref: https://cloud.google.com/iap/docs/identity-howto#getting_the_users_identity_with_signed_headers
closes #CONSVC-2120

fix: remove header prefix for openidc

---

.env.example
consvc_shepherd/settings.py
openidc/middleware.py
openidc/test_middleware.py
requirements.in
requirements.txt

Using JWT is preferred over using simply the google email header.
I've made changes so that the email header should work when `debug=True`. It should also work if the email header isn't there.
JWT validation only occurs when `debug=False`

fix: auth gcp jwt header[MERGE ON HOLD]

---

requirements.in
requirements.txt

While trying out the IAP JWT workflow we ran into: "IAP JWT validation error: The key algorithm ES256 requires the cryptography package to be installed.".

fix: add python package for IAP jwt

---

consvc_shepherd/forms.py
consvc_shepherd/models.py
consvc_shepherd/tests/test_forms.py
consvc_shepherd/tests/test_views.py
consvc_shepherd/urls.py
consvc_shepherd/views.py
templates/index.html

The overview page includes:
- a table view of the latest Snapshot.
- two select input so that a user can get the difference between to snapshots
The difference logic only accounts for the addition and or removal of advertisers,
I will put the advertiser hosts/paths logic as a follow up, as this is quite a bit already.

feat: add Shepherd Overview Page

---

consvc_shepherd/forms.py

Currently the compare snapshot ui dropdowns don't update when new setting snapshots are created, seems like setting choices like below doesn't dynamically get new snapshots
``` 
choices=(
(snapshot.name, snapshot)
for snapshot in SettingsSnapshot.objects.all().order_by("-created_on")
) 
```

[DISCO-2304] fix: UI snapshot dropdowns update with new snapshots

---

schema/shepherd.schema.json
schema/test_schema.py

🙈 ... didn't account for Advertiser names with spaces and special characters
not sure if there is a more efficient way to specify all characters?

fix: Advertiser Name json schema field to allow all characters

---

.gitignore
consvc_shepherd/admin.py
consvc_shepherd/settings.py
consvc_shepherd/storage.py

Adding env variable in settings.py for a new file name, to support the new allocation json file while supporting previous adM filtering file.
Modify [storage.py](https://github.com/mozilla-services/consvc-shepherd/blob/main/consvc_shepherd/storage.py) to have an additional parameter to set a different file name.
Made change to base call of `send_to_storage` with parameter of `file_name` defined, so that current function is maintained and `GS_BUCKET_FILE_NAME` still supplied for adM filter file. 
A couple type annotations added as well. We discussed we'd like to add them as we go and make changes to have Shepherd fall more in line with mypy typing across the board.

[DISCO-2361] New Allocation File Capabilities

---

Makefile
consvc_shepherd/models.py
consvc_shepherd/tests/factories.py
consvc_shepherd/tests/test_admin.py
contile/models.py
poetry.lock
pyproject.toml

JIRA: [DISCO-2159](https://mozilla-hub.atlassian.net/browse/DISCO-2366)
GitHub: [#109 ](https://github.com/mozilla-services/consvc-shepherd/issues/109)
Implement the addition of mypy as a Makefile command and that all files conform to correct typing.
Requires:
Pyproject.toml updates
Test build with poetry install and ensure no dependency issues with mypy version (poetry lock --no-update)
Updates to makefile to run mypy checks
Resolve any typing errors mypy throws
Add process to lint checks when verifying code quality 
Add ignore annotations to inaccurate typing errors
[DISCO-2159]: https://mozilla-hub.atlassian.net/browse/DISCO-2159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2159] Add mypy/types to Shepherd

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md

JIRA: [DISCO-2379](https://mozilla-hub.atlassian.net/browse/DISCO-2379)
GitHub: [#111 ](https://github.com/mozilla-services/consvc-shepherd/issues/111)
In order to promote quality and meet GitHub recommended community standards, this task is to add a pull request template to the consvc-shepherd project. Furthermore, other services like Merino and Contile have had this convention implemented and enforced.
Also adds the `contributing.md` document like in all our repositories with updates to Shepherd specific details.
[GitHub Docs on PR Templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
[DISCO-2310]: https://mozilla-hub.atlassian.net/browse/DISCO-2310?atlOrigin=eyJpIjoiNWRkNTljNzY …

[DISCO-2379] Add Pull Request Template to consvc-shepherd

---

consvc_shepherd/settings.py
consvc_shepherd/urls.py
poetry.lock
pyproject.toml

JIRA: [DISCO-2399](https://mozilla-hub.atlassian.net/browse/DISCO-2399)
GitHub: [#118 ](https://github.com/mozilla-services/consvc-shepherd/issues/118)
Since the addition of pydocstyle, we can take advantage of Django’s capabilities to generate documentation. This allows for clean, easy to read documentation of all the views and models. This can be accessed at the admin/doc endpoint.
See:
[Django documentation](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/admindocs/)
[docutils](https://pypi.org/project/docutils/)
Acceptance Criteria:
Add code to generate application docs/runbook at admin/doc endpoint.
Add docutils
[DISCO-2399]: https://mozilla-hub.atlassian.net/browse/DISCO-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

[DISCO-2399] Add Auto-generated Documentation to Django Admin

---

consvc_shepherd/models.py
consvc_shepherd/tests/test_admin.py
consvc_shepherd/tests/test_models.py
schema/allocation.schema.json

JIRA: [DISCO-2397](https://mozilla-hub.atlassian.net/browse/DISCO-2397)
Added a UUID field to Partner Model.
Changes to schema and tests to adjust for new field.
[DISCO-2397]: https://mozilla-hub.atlassian.net/browse/DISCO-2397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2397] fix: Schema change

---

Makefile
consvc_shepherd/settings.py
consvc_shepherd/tests/test_version.py
consvc_shepherd/version.py
poetry.lock
pyproject.toml

JIRA: [DISCO-2407](https://mozilla-hub.atlassian.net/browse/DISCO-2407)
GitHub: [#122 ](https://github.com/mozilla-services/consvc-shepherd/issues/122)
As part of verifying application stability and integrity, we want Shepherd to emit data to Sentry which we can monitor. 
Sentry boilerplate is in place, but there is no current project, associated DSN, environments or enabled logic in Shepherd.
Acceptance Criteria:
Sentry Project created
DSN Env variables deployed to cloudops-infra
Sentry config in Shepherd updated
Environment specific tagging in place (possibly)
[DISCO-2407]: https://mozilla-hub.atlassian.net/browse/DISCO-2407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2407] Shepherd Sentry Setup

---

Makefile
consvc_shepherd/models.py
consvc_shepherd/storage.py
consvc_shepherd/tests/test_admin.py
consvc_shepherd/tests/test_models.py
contile/admin.py
pyproject.toml

JIRA: [DISCO-2366](https://mozilla-hub.atlassian.net/browse/DISCO-2366)
GitHub: [#107](https://github.com/mozilla-services/consvc-shepherd/issues/107)
Shepherd is missing some of the useful features to verify test coverage and conventions we have for Merino. A simple update of the pyproject.toml and update of Poetry dependencies will give us access to:
Test coverage percentage reporting
Addition of mypy static typing 
pydocstyle 
Test coverage report
Individual commands for flake9, bandit, black, isort, mypy, pydocstyle
There is also an error with the local make call to test and it only runs with ./manage.py test, which doesn’t provide the same clear output.
Note: many features covered by other individual PRs for each tool.
[DISCO-2366]: …

[DISCO-2366] Expand Automated Coverage 

---

consvc_shepherd/forms.py
consvc_shepherd/tests/test_forms.py

JIRA: [DISCO-2421](https://mozilla-hub.atlassian.net/browse/DISCO-2421)
Currently, where there is a blank form for PartnerAllocation, Shepherd 500s since it takes its values as None and tries to use it to find the sum of percentages. This fixes so that a completely empty form is ignored. A partially completed form will cause validation errors from the model.
[DISCO-2421]: https://mozilla-hub.atlassian.net/browse/DISCO-2421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2421] fix: ignore blank forms when validating AllocationFormset

---

contile/admin.py

JIRA: [DISCO-2422](https://mozilla-hub.atlassian.net/browse/DISCO-2422)
So we can have Advertisers listed by alphabetical order, which makes it easier to reference
[DISCO-2422]: https://mozilla-hub.atlassian.net/browse/DISCO-2422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2422] fix: Sort Advertiser by name in django admin

---

consvc_shepherd/admin.py
consvc_shepherd/tests/test_admin.py
consvc_shepherd/tests/test_models.py
schema/allocation.schema.json
schema/test_schema.py

JIRA: [DISCO-2425](https://mozilla-hub.atlassian.net/browse/DISCO-2425)
We want to add guardrails to ensure that AllocationSetting information is selected when publishing SOV
[DISCO-2425]: https://mozilla-hub.atlassian.net/browse/DISCO-2425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Guardrails to require allocation to correspond to first two tiles

---

consvc_shepherd/settings.py
contile/models.py

JIRA: [DISCO-2423](https://mozilla-hub.atlassian.net/browse/DISCO-2423)
GitHub: [#138 ](https://github.com/mozilla-services/consvc-shepherd/issues/138)
Currently we have all the countries listed for Adops to select, this can cause some user error (ie selecting “United Kingdom” vs “United States”) as there’s too many to select from. It’s also annoying to scroll through all of them.
Upon doing some research, it appears that the [`django-countries`](https://github.com/SmileyChris/django-countries) library we use to generate the `CountryField` dropdown has configuration options that can be defined. No need for using db migrations and switching to `CharField`. In `settings.py`, the defined countries and a sorting flag are set. Therefore, we can easily add countries on the fly that won't …

[DISCO-2423] Switch Country Select to only use smaller subset of countries

---

consvc_shepherd/settings.py

JIRA: [DISCO-2447](https://mozilla-hub.atlassian.net/browse/DISCO-2447)
GitHub: [#144 ](https://github.com/mozilla-services/consvc-shepherd/issues/144)
Sentry sent an email indicating this feature is out of beta and will become a subscription service. We don’t find this super useful for Merino and won’t need it for Shepherd, so  disabling it.
[DISCO-2447]: https://mozilla-hub.atlassian.net/browse/DISCO-2447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2447] chore: Disable Sentry transcations for Shepherd

---

consvc_shepherd/settings.py

JIRA: [DISCO-TODO](https://mozilla-hub.atlassian.net/browse/DISCO-TODO)
GitHub: [#TODO](https://github.com/mozilla-services/consvc-shepherd/issues/TODO)
Rename of `SENTRY_MODE` repr.  Forgot to roll into the update with profiling trace sample rate.

Rename SENTRY_MODE env var

---

consvc_shepherd/admin.py
consvc_shepherd/forms.py
consvc_shepherd/settings.py
consvc_shepherd/urls.py
consvc_shepherd/utils.py
contile/admin.py

JIRA: [DISCO-2420](https://mozilla-hub.atlassian.net/browse/DISCO-2420)
GitHub: [#139 ](https://github.com/mozilla-services/consvc-shepherd/issues/139)
There are a number of available customization options that can be implemented in the Django Admin page. This would remove some of the defaults in the UI/UX that default to Django and would allow for an improved UI with greater cohesion to the application.
Changes:
- alphabetical ordering of Partners to match alphabetical ordering elsewhere
- numeric ordering of partner_allocations so first tile position shows up first (more intuitive)
- Renaming of site title, header and index title to rename from default Django Admin to "Shepherd" and "Advertiser Settings Manager"
- Removed redundant `if_enabled` suffix on all metrics calls
- Enable nav …

[DISCO-2420] Shepherd Admin Optimizations

---

consvc_shepherd/models.py
consvc_shepherd/views.py
templates/allocation/allocation_list.html
templates/base.html

JIRA: [DISCO-2458](https://mozilla-hub.atlassian.net/browse/DISCO-2458)
A small step to shuffle things away from django admin
[DISCO-2458]: https://mozilla-hub.atlassian.net/browse/DISCO-2458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2458] feat: Display latest launched allocation snapshot on List Page

---

consvc_shepherd/forms.py
consvc_shepherd/tests/test_forms.py
consvc_shepherd/tests/test_views.py
consvc_shepherd/views.py
schema/allocation.schema.json
templates/allocation/allocation_list.html

Moving publishing allocation snapshot away from django admin. eliminates two step publishing, which i think is okay, since the number of allocations is small

feat: allocationsettings ui

---

consvc_shepherd/views.py

JIRA: [DISCO-2494](https://mozilla-hub.atlassian.net/browse/DISCO-2494)
GitHub: [#155](https://github.com/mozilla-services/consvc-shepherd/issues/155)
custom ui currently uses the wrong file name when sending settings to the GCS bucket. As a result it overwrites the adm settings file, which we don’t want.
[DISCO-2494]: https://mozilla-hub.atlassian.net/browse/DISCO-2494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2494] fix: use correct file name when sending alloc to GCS

---

schema/allocation.schema.json
schema/test_schema.py

JIRA: [DISCO-2545](https://mozilla-hub.atlassian.net/browse/DISCO-2545)
GitHub: [#163](https://github.com/mozilla-services/consvc-shepherd/issues/163)
We will eventually want to have SOV for the third tile, this allows the schema to be less strict about allocations.
I don't think this should affect the existing behaviour of two allocations either
[DISCO-2545]: https://mozilla-hub.atlassian.net/browse/DISCO-2545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2545] feat: Allow 3 sov allocations in schema

---

PULL_REQUEST_TEMPLATE.md

JIRA: [DISCO-2572](https://mozilla-hub.atlassian.net/browse/DISCO-2572)
Remove the GitHub issue link from the Pull Request Templates
[DISCO-2572]: https://mozilla-hub.atlassian.net/browse/DISCO-2572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2572] remove github link from pr template

---

Makefile
docker-compose.test.yml
docker-compose.yml
docs/testing.md

JIRA: [DISCO-2574](https://mozilla-hub.atlassian.net/browse/DISCO-2574)
Because we switch to a docker workflow, the existing `make test` does not work
[DISCO-2574]: https://mozilla-hub.atlassian.net/browse/DISCO-2574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DISCO-2574] Ability to run tests using docker workflow

---

docs/intro.md

The diagram was originally using the "LR" direction which made it hard to read, as the items of the diagram were small.
Dark theme for readability in darker backgrounds, which i think is the default for mdbook?

chore: update mermaid diagram

---

consvc_shepherd/preview.py
consvc_shepherd/settings.py
consvc_shepherd/static/preview/css/preview.css
static/preview/css/preview.css
templates/preview.html

JIRA: [AE-388](https://mozilla-hub.atlassian.net/browse/AE-388)
This is a follow-up to #196 to tweak the previews page:
1. It fixes the styling of Tiles such that long tile titles get correctly truncated.
2. It adds an Environment drop-down to let users pick between 3 environments:
* Dev uses MARS Staging, and the dev network and site in Kevel
* Preview uses MARS Prod, and the preview/staging site in the Kevel prod network
* Prod uses MARS Prod and the prod network and site in Kevel
With this change we no longer use the MARS_URL environment variable, which I'll remove after this lands.
[AE-388]: https://mozilla-hub.atlassian.net/browse/AE-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AE-388] Tweaks to the preview page

---

consvc_shepherd/preview.py
pyproject.toml
templates/preview.html

[AE-421](https://mozilla-hub.atlassian.net/browse/AE-421)
- ads being requested via unified api, not yet mapping response to the same shape
- removed preview env since those placements don't yet exist, map response to tile/spoc for preview page, pass in country to enable the translation
We want to be able to preview the unified api, and now that we have the preview page that is a good first use case to see the API return spocs and tiles in order for them to be rendered there.
Add new environments for similar scenarios but served via the unified api.
Note: the country/region dropdown currently does not get passed through the request; the ability to override regions & countries for testing purposes is still TBD in unified api.
The country dropdown only modifies the translated string …

Add unified api options to preview page

---

consvc_shepherd/preview.py

[AE-421](https://mozilla-hub.atlassian.net/browse/AE-421)
follow up from https://github.com/mozilla-services/consvc-shepherd/pull/200
the tiles format has now been created, so responses to the tiles placement will be in that shape.
related
https://github.com/mozilla-services/mars/pull/165
https://github.com/mozilla-services/mars/blob/main/unified_ads_api/formats.go#L75-L80
[AE-421]: https://mozilla-hub.atlassian.net/browse/AE-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update tiles reponse parsing for unified api preview page

---

consvc_shepherd/preview.py
consvc_shepherd/tests/test_preview.py
consvc_shepherd/tests/test_views.py
docker-compose.test.yml
docker-compose.yml
docs/quickStart.md
templates/preview.html

JIRA: [AE-416](https://mozilla-hub.atlassian.net/browse/AE-416)
This PR adds adds "direct sold tiles" to the Tiles section on the Preview page, fetched by requesting `sponsored-topsite` placements from the `/spocs` endpoint. In this view, they are added to the right of the tiles coming from `/v1/tiles`.
Note that this new functionality is for showing the direct sold tiles when selecting Preview, Dev, and Prod environments from the dropdown. For unified API, those are pulled in on the backend already, and don't need to be put together by the client.
[AE-416]: https://mozilla-hub.atlassian.net/browse/AE-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AE-416] Show direct sold tiles on preview page

---

consvc_shepherd/static/preview/css/preview.css
static/preview/css/preview.css
templates/preview.html

JIRA: [AE-480](https://mozilla-hub.atlassian.net/browse/AE-480)
#209 caused a regression in how desktop SPOCs are displayed on the Shepherd Preview page. This fixes the styling for SPOCs such that they vertically expand to match the height of the tallest SPOC in the row.
Before:
After:
Also moves styling for links to CSS.
[AE-480]: https://mozilla-hub.atlassian.net/browse/AE-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AE-480] Fix SPOC vertical sizing on Preview page

---

consvc_shepherd/preview.py

JIRA: [AE-479](https://mozilla-hub.atlassian.net/browse/AE-479)
Direct sold tiles were using the wrong field for the title display.
[AE-479]: https://mozilla-hub.atlassian.net/browse/AE-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AE-479] fix shepherd preview page uses wrong field for direct sold tile titles

---

Makefile
consvc_shepherd/preview.py

In #215 I noted I think we should stop ignoring PEP-8 conventions, but it might require changing a lot of files.
It turned out to be way easier than I expected, so this drops all ignored rules, except increasing the max line length to 120 characters (the default 79 characters is too short for modern screens, and we surpass it on >150 lines of code already).t

Remove flake8 exceptions

---

consvc_shepherd/preview.py
consvc_shepherd/settings.py

JIRA: [AD--456 Update MARS preview environment to allow the new regions via shepherd updte](https://mozilla-hub.atlassian.net/browse/AD-456)
Launching a test of Sponsored Tiles on desktop into 6 new EU markets (Poland, Austria, Netherlands, Luxembourg, Switzerland and Belgium). This update makes it easy to preview the tiles using the MARS Ads Preview Tool.
- [] [Documentation](https://github.com/mozilla-services/consvc-shepherd/tree/main/docs) has been updated (if applicable).
- [] Functional and performance test coverage has been expanded and maintained (if applicable).

Ad 456 update mars preview environment to allow the new regions via shepherd update

---

consvc_shepherd/preview.py
consvc_shepherd/tests/test_preview.py
templates/preview.html

The use of "User Agent" on the preview page is an unnecessary implementation detail. Replace this with a more friendly "Form Factor" instead.
Also use shorter slugs for form factors (desktop, mobile) instead of passing the entire UA string in the query parameter.

Use Form Factor instead of User Agent in Preview UI

---

consvc_shepherd/management/commands/sync_boostr_data.py
consvc_shepherd/tests/test_sync_boostr.py
docs/SUMMARY.md
docs/operations/syncBoostrData.md

JIRA: [AE-532](https://mozilla-hub.atlassian.net/browse/AE-532)
@cbguder [made a good point](https://github.com/mozilla-services/consvc-shepherd/pull/215#discussion_r1702065723) on the last iteration of the Boostr sync script, that the `while True` loop is dangerous and might not ever finish if we receive something unexpected back from the API.
This change addresses that by adding an upper limit of how many times we fetch deals pages. It is set up for a default max of `50`, and can be adjusted by passing an optional parameter to the script.
[AE-532]: https://mozilla-hub.atlassian.net/browse/AE-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AE-532] Add upper limit to boostr deals fetching

---

consvc_shepherd/tests/test_preview.py
pyproject.toml

JIRA: [AE-535](https://mozilla-hub.atlassian.net/browse/AE-535)
This PR adds unit tests for the `get_amp_tiles` and `get_spocs_and_direct_sold_tiles` functions. The goal is to ensure that we correctly extract the expected keys and values from their responses and use them as intended in our views.
[AE-535]: https://mozilla-hub.atlassian.net/browse/AE-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AE-535] Add unit tests for get_amp_tiles and get_spocs_and_direct_sold_tiles functions

---

consvc_shepherd/management/commands/sync_boostr_data.py
consvc_shepherd/tests/test_sync_boostr.py

JIRA: [AE-534](https://mozilla-hub.atlassian.net/browse/AE-534)
Recently, Boostr surprised us by [introducing rate limits to the API](https://help.boostr.com/en/articles/9006378-public-api-rate-limits-and-best-practices). This simple change:
- Refactors the script to have a wrapper for Boostr Api requests
- Slows down requests by an interval that's just slower than what the Boostr rate limit allows. This keeps us under their rate limits and not needing to handle 429s, but we can add that in a subsequent PR if it becomes necessary
I'm thinking this will unlock the ability to run the script in all environments when @cyptm's scheduled job changes land, even though it runs slower, that should be fine.
Longer term, we can look at other ways to limit the amount of data we are pulling by …

[AE-534] Respect the rate limits

---

docs/operations/syncBoostrData.md

We missed some `README` updates for the way the boostr sync script accepts the API credentials, so just adding them now. 
Reviewer, please take a look over the sync script docs and make sure I haven't missed anything else.
- [-] The PR title starts with the JIRA issue reference, format `[DISCO-####]`, and has the same title (if applicable).
- [-] Functional and performance test coverage has been expanded and maintained (if applicable).

Update sync_boostr_data usage documentation

---

consvc_shepherd/preview.py
consvc_shepherd/tests/test_preview.py

Jira: [AE-554](https://mozilla-hub.atlassian.net/browse/AE-554)
Renames the `user_context_id` variable to `context_id` to make it more clear that this is not aggregating user data.
Related Jira [AE-519](https://mozilla-hub.atlassian.net/browse/AE-519).
```
make local-test
app-1  | Required test coverage of 95% reached. Total coverage: 96.73%
app-1  | ================== 65 passed, 1 skipped, 5 warnings in 1.59s ===================
app-1 exited with code 0
```
Unified API Environments (prod/dev) are both working again:
[AE-554]: https://mozilla-hub.atlassian.net/browse/AE-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AE-519]: https://mozilla-hub.atlassian.net/browse/AE-519?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

[AE-519] Rename user_context_id to context_id

---

PULL_REQUEST_TEMPLATE.md

[AE-451](https://mozilla-hub.atlassian.net/browse/AE-541)
- We noticed that the PR template references out of date projects like DISCO
- We've recently switched the repo over to squash merging with the PR title as the subject of the commit, and the PR description as the body of the commit, so the existing template no longer makes sense in that context
Update the template to support engineers in providing a good description.
Remove the checklist as that will appear with every PR description in our history and isn't useful metadata about the commit in that context. I'd like to look for another place for such a checklist, perhaps in the contribution guidelines?
I'm not sure if there is a way to test-drive this before merging, but I did use the new format for this PR. And I checked the …

[AE-451] Improve the Shepherd PR template

---

consvc_shepherd/management/commands/sync_boostr_data.py
consvc_shepherd/tests/test_sync_boostr.py
docs/operations/syncBoostrData.md
docs/quickStart.md

I am not sure that the current request rate setting will allow the script to do a full sync given the Boostr API's rate limits, based on some quick tests I've run. As we're preparing to merge our scheduled job to run this script in all environments on a regular basis, I thought it would be helpful to be able to configure this value. 
* Set up a parameter for the request rate instead of hard coding it, meaning this value can be configurable without making a PR and pushing a code change here.
* Set the default value of requests every 1 seconds for the script. At this default setting, I have managed a successful full sync of the current boostr data in 45 minutes.
* A few additional documentation updates, fixes, and helpful tips
The specs verify that the Boostr api wrapper code does in fact …

Set default request rate to 1 per second for the boostr sync script

---

.gitignore
Makefile
poetry.lock
pyproject.toml
ruff.toml

[SHEP-38](https://mozilla-hub.atlassian.net/browse/SHEP-38)
I've noticed a few tasks we  all have to do that are frequent or take multiple steps that are often forgotten when needed. I've added them to our Makefile to streamline development tasks.
I also cleaned up the formatting & arrangement  of the .PHONY commands and improved some of the help descriptions
modified `make makemigrations` behavior it will now make migrations and automatically migrate. If you just want to create migrations without the migrate run `make makemigrations MIGRATE=false`
added `make ruff` this uses the newer faster ruff linter instead of the multiple tools we currently use. The setting are still being tuned to match the older settings.
added `make debug` uses [docker …

Shep 38 makefile improvements

---

consvc_shepherd/settings.py
consvc_shepherd/tests/test_admin.py
poetry.lock
pyproject.toml

[SHEP-43](https://mozilla-hub.atlassian.net/browse/SHEP-43)
When we ran our tests, a few warnings appeared. While they don't cause the tests to fail and are easy to ignore, I decided to investigate and fix them. By addressing these warnings, we can make our code more reliable and reduce potential issues when updating to the next version of Django.
This PR fixes warnings we encountered when we ran our tests. Here is an overview of changes:
1. `RemovedInDjango51Warning: The DEFAULT_FILE_STORAGE setting is deprecated`: 
- Django 4.2 changed how storage objects are configured so its easier to configure multiple storage objects. As a result, DEFAULT_FILE_STORAGE has been deprecated in favor of STORAGES. DEFAULT_FILE_STORAGE will be removed on Django 5.1.
- For more info check [Google Cloud …

Test warning improvements

---

consvc_shepherd/preview.py
consvc_shepherd/settings.py

[SHEP-66](https://mozilla-hub.atlassian.net/browse/SHEP-66)
[SHEP-65](https://mozilla-hub.atlassian.net/browse/SHEP-65)
We will be launching tiles in new regions, so we need to show these new countries in the shepherd preview UI.
- Add Singapore (SG), Sweden (SE), Netherlands (NL) and Japan (JP) to the list of countries in shepherd supports.
Run locally and see that these countries show up in the dropdown.
[SHEP-66]: https://mozilla-hub.atlassian.net/browse/SHEP-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SHEP-65]: https://mozilla-hub.atlassian.net/browse/SHEP-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SHEP66/65: Add new countries to preview

---

Makefile
ruff.toml

[SHEP-76](https://mozilla-hub.atlassian.net/browse/SHEP-76)
We currently use 6 different linting tools which can tend to be slow to run multiple times during the dev cycle.
Experiment with consolidating most of the linters to [ruff](https://astral.sh/ruff) a modern fast linter and code formatter written in rust.  We'll benefit from a faster linting process and consolidation to just 2 tools (ruff and mypy)
Test `make lint-fix` and compare with `make ruff`
make ruff should fix everything make lint-fix can do, with a noticeable difference that it will format all line lengths to max 120 chars. See #216 for past discussion on this change
[SHEP-76]: https://mozilla-hub.atlassian.net/browse/SHEP-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Shep 76 makefile improvements enhance ruff

---

consvc_shepherd/preview.py
consvc_shepherd/tests/test_preview.py

The /v1/tiles endpoint returns a 204 response with no body when there are no tiles available. Currently when this happens, get_amp_tiles raises an exception, and we don't display any ads (even if e.g. SPOCs might be available):
This changes get_amp_tiles to gracefully handle a 204 response from /v1/tiles and allows the preview page to display other ads that migth be available.
This can be tricky to verify, as tiles _should_ almost always available for the countries/regions currently supported by the preview page. However, at time of writing, they are not available for Canada, as seen in the above screenshot.
To verify:
1. Go to the Preview page
2. Pick a country/region where tiles are not available, and hit Preview
3. Observe that SPOCs are shown

Gracefully handle 204 responses from /v1/tiles on Preview page

---

.gitignore
consvc_shepherd/management/commands/sync_bq_data.py
consvc_shepherd/tests/test_sync_bq_data.py

[SHEP-70](https://mozilla-hub.atlassian.net/browse/SHEP-70)
We received feedback from the Ad Ops folks that it would be good to see the flight name in the Delivered Flights table as well. This PR includes the flight_name to the BQ query in the sync_bq_script.
- Update `sync_bq_data` script to also query for the flight name
- Update `test_sync_bq_data` tests to also include and test the flight name
1. Start Shepherd with `docker compose up --build`
1. Pass your gcloud credentials to the shepherd container to access the BigQuery view `moz-fx-data-shared-prod.ads.consolidated_ad_metrics_daily_pt`:
1. Login to gcloud locally `gcloud auth application-default login`.
2. Copy your gcloud creds into the shepherd container:
```bash
docker cp ~/.config/gcloud/application_default_credentials.json …
```

[SHEP-70]: Add flight_name to BQ query in sync_bq_script

---

docs/SUMMARY.md

[SHEP-17](https://mozilla-hub.atlassian.net/browse/SHEP-17)
New docs need to be added to our table of contents file so they show up in our [standalone doc](https://mozilla-services.github.io/consvc-shepherd/intro.html).
- Add Sync BQ Data documentation to table of contents
- Run the docs locally (follow doc make targets in our Makefile) and you should see two new Sync BQ data docs showing up [here](https://mozilla-services.github.io/consvc-shepherd/operations/index.html)
[SHEP-17]: https://mozilla-hub.atlassian.net/browse/SHEP-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SHEP-17]: Publish sync bq data docs

---

ad-ops-dashboard/README.md
consvc_shepherd/settings.py

[SHEP-92](https://mozilla-hub.atlassian.net/browse/SHEP-92)
CSRF authentication needs to be added for the APIs, as Django returns CSRF authentication errors on POST, PATCH, and DELETE requests.
Added the CSRF Origins array.
Made the authentication classes empty to resolve the CSRF authentication issue since Open IDC authentication is applied.
You can test the fix by removing the empty authentication class to check csrf errors. To find out how Open IDC authentication conflicts with Django authentication, we can remove the OpenIDC authentication and use the default Django authentication classes. This should not return any CSRF-related errors.
[SHEP-92]: https://mozilla-hub.atlassian.net/browse/SHEP-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

[SHEP-92] csrf authentication error fix

---

consvc_shepherd/management/commands/sync_bq_data.py
consvc_shepherd/tests/test_sync_bq_data.py

[SHEP-17](https://mozilla-hub.atlassian.net/browse/SHEP-17)
[Andre suggested](https://github.com/mozilla-it/webservices-infra/pull/2900#discussion_r1797262801) it would be easier to configure the infra side if the script handled the project-id logic (instead of configuring the k8s job to use that info).
- Use  a default project id `moz-fx-ads-prod` to query BQ
- Add tests for the default project id
- Run shepherd and exec with `make debug`
- Run the script without providing a project ID with  `python manage.py sync_bq_data` and check that the script runs successfully.
- Try passing a different project id with ``python manage.py sync_bq_data --project_id "moz-fx-ads-nonprod"` and check that the script runs successfully
- Run the tests
[SHEP-17]: …

[SHEP-17] - Add a default project-id to BQ sync script

---

Makefile
ad-ops-dashboard/jest.config.js
ad-ops-dashboard/package.json

[SHEP-137](https://mozilla-hub.atlassian.net/browse/SHEP-137)
We have been seeing [an error pop up in CI](https://app.circleci.com/pipelines/github/mozilla-services/consvc-shepherd/1568/workflows/93d616ab-aa3f-4361-8dbd-8bcc5e5a1618/jobs/4925) when running the jest tests, "A jest worker process was terminated by another process". The issue is coming from the fact that jest's default behavior is spinning up a worker pool to run tests, with as many workers as there are cores on the machine, which doesn't work in CI.
Spinning up this worker pool itself has performance costs, and its better to tune the jest config for almost all cases. For local development, it's better to set the workers to a relative value (50%). For CI, it's better to run in serial instead of spin up workers …

[SHEP-137] Tune jest config for CI, local testing, and watch mode

---

.env.example
Makefile
consvc_shepherd/management/commands/sync_boostr_data.py
consvc_shepherd/settings.py
manage.py

[SHEP-36](https://mozilla-hub.atlassian.net/browse/SHEP-36)
After speaking with @mashalifshin it sounds like we wanted to expand on this ticket to include an entire custom local logging formatted. This will allow us to not only add human readable timestamps, but also allow for us, in the future, to have more verbose, "local specific" logging that can help with debugging.
We've added a new formatter called `localdev` to `settings.py` file. This is enabled when the env variable `CUSTOM_LOCAL_LOGGER_ENABLED` is set to true and disabled by default or when explicitly set to false. This new logging formatter will display most of the fields similar to the JSON logger with some small changes.
1. The log level has been moved to a header and in human readable format (rather than a number value)
2. …

[SHEP-36] Adding additional flexibility to local logging

---

consvc_shepherd/settings.py

This is a hotfix follow-up to [this](https://github.com/mozilla-services/consvc-shepherd/commit/2b9e0716265d85bf0ea9dc9d07d4791fdbb9cd28)
The error following error is occurring in staging when trying to run the boostr script: `django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`
I can't seem to recreate this locally, but it appears this is likely the right fix. Curious if folks who have better django knowledge can have some input here.

[SHEP-36] Hotfix for failing script in staging.

---

consvc_shepherd/settings.py
manage.py

Found the issue for failing builds. Accidentally removed the deceleration of the os env that sets the global settings.py path for django.

[SHEP-36] BUG FIX: accidently removed settings env variable setting path.
